### localhost all contacts
GET http://localhost:3000/contacts

### localhost single contact
GET http://localhost:3000/contacts/650f08224b575470917e4371

### render all contacts
GET https://three41-web-server.onrender.com/contacts

### render single contact
GET https://three41-web-server.onrender.com/contacts/650f08224b575470917e4371
