###Post in localhost:3030
POST http://localhost:3030/users
Content-Type: application/json

{
  "username": "Kerplunk",
   "fullName": "Rob perkins",
   "email": "thisemail@geemail.com",
   "password": "thisPassword",
   "tasksAssigned": []
}

### GET all users in localhost:3030
GET http://localhost:3030/users

### POST in Render
POST https://task-manager-hc4o.onrender.com/users
Content-Type: application/json

{
  "username": "Fuzzy Bunny Slippers",
   "fullName": "Jan Gilbert",
   "email": "fuzzyBunny@geemail.com",
   "password": "thisPassword",
   "tasksAssigned": []
}

### GET all users on Render
GET https://task-manager-hc4o.onrender.com/users